apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregators-config
data:
  APP_ENV: "production"
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
  CONNECTORHUB_URL: "http://connectorhub:8080"
  CATALOG_URL: "http://catalog:8080"
  ORDERING_URL: "http://ordering:8080"
