apiVersion: v1
kind: ConfigMap
metadata:
  name: floor-config
data:
  APP_ENV: "production"
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
  KITCHEN_URL: "http://kitchen:8080"
  BILLING_URL: "http://billing:8080"
  SETTINGS_URL: "http://settings:8080"
  ORDERING_URL: "http://ordering:8080"
