// Package domain holds the pure identity model and rules. It imports no
// infrastructure (no pgx, no connect, no jwt signing) — only standard library
// and the shared common proto enums used as value types.
package domain

import (
	"errors"
	"time"

	commonv1 "github.com/restorna/platform/gen/go/restorna/common/v1"
	identityv1 "github.com/restorna/platform/gen/go/restorna/identity/v1"
)

// Typed domain errors. The grpc adapter maps these to Connect codes via
// pkg/errors.ToConnect; the domain never panics for expected conditions.
var (
	ErrUserNotFound      = errors.New("user not found")
	ErrUserInactive      = errors.New("user inactive")
	ErrChallengeNotFound = errors.New("otp challenge not found")
	ErrChallengeExpired  = errors.New("otp challenge expired")
	ErrChallengeConsumed = errors.New("otp challenge already used")
	ErrTooManyAttempts   = errors.New("too many otp attempts")
	ErrCodeMismatch      = errors.New("otp code mismatch")
	ErrInvalidAddress    = errors.New("invalid address")
	ErrInvalidChannel    = errors.New("invalid channel")
)

// Realm separates the platform control plane from tenant principals.
type Realm = identityv1.Realm

// Channel is the OTP delivery medium.
type Channel = identityv1.Channel

// User is a principal that can authenticate. Identity is cross-tenant: a User
// row is not bound to an owner/brand/restaurant. Tenant scope is attached only
// when a scoped token is issued.
type User struct {
	ID          string
	Email       string
	Phone       string
	DisplayName string
	Realm       Realm
	Active      bool
	CreatedAt   time.Time
}

// NewUser builds an active user for the given realm. ID is generated by the
// caller (app layer, via pkg/ids) so the domain stays free of infra concerns.
func NewUser(id, address string, channel Channel, realm Realm) User {
	u := User{ID: id, Realm: realm, Active: true, CreatedAt: time.Now().UTC()}
	switch channel {
	case identityv1.Channel_CHANNEL_EMAIL:
		u.Email = address
	case identityv1.Channel_CHANNEL_PHONE:
		u.Phone = address
	}
	return u
}

// EnsureActive returns ErrUserInactive for a disabled principal.
func (u User) EnsureActive() error {
	if !u.Active {
		return ErrUserInactive
	}
	return nil
}

// RoleForRealm is the default role granted on a fresh (unscoped) login. A
// scoped token (IssueScopedToken) later narrows this to a concrete tenant role.
func RoleForRealm(r Realm) commonv1.Role {
	if r == identityv1.Realm_REALM_PLATFORM {
		return commonv1.Role_ROLE_PLATFORM_ADMIN
	}
	return commonv1.Role_ROLE_OWNER
}
