// Package domain holds the pure staff model and rules. It imports no
// infrastructure (no pgx, no connect, no nats) — only the standard library and
// the shared common proto enums used as value types.
//
// The staff bounded context owns the roster of people working in an outlet and
// their RBAC role bindings. It ENFORCES plan limits: every role that occupies a
// quota slot ("staff.<role>") must have a reservation in entitlements before the
// member is persisted, and that reservation is released when the member is
// deactivated or moved off the role.
package domain

import (
	"errors"
	"fmt"
	"strings"
	"time"

	commonv1 "github.com/restorna/platform/gen/go/restorna/common/v1"
)

// Typed domain errors. The grpc adapter maps these to Connect codes; the domain
// never panics for expected conditions.
var (
	ErrStaffNotFound  = errors.New("staff member not found")
	ErrInvalidName    = errors.New("staff name is required")
	ErrInvalidContact = errors.New("staff email or phone is required")
	ErrInvalidRole    = errors.New("staff role is invalid")
	ErrNotInScope     = errors.New("staff member not in tenant scope")
	ErrAlreadyActive  = errors.New("staff member already active")
	ErrAlreadyInactive = errors.New("staff member already inactive")
	ErrSameRole       = errors.New("staff member already has that role")
)

// Member is a person on an outlet's roster with a single RBAC role. Tenancy is
// explicit (owner/brand/restaurant) so rows can be RLS-scoped and quota can be
// reserved against the owner.
type Member struct {
	ID           string
	OwnerID      string
	BrandID      string
	RestaurantID string
	Name         string
	Email        string
	Phone        string
	Role         commonv1.Role
	Active       bool
	UserID       string // linked identity user, set after they accept an invite
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// NewMember builds an active roster member. The ID is generated by the caller
// (app layer, via pkg/ids) so the domain stays free of infra concerns. It
// validates the inputs and the role.
func NewMember(id string, scope Scope, name, email, phone string, role commonv1.Role) (Member, error) {
	name = strings.TrimSpace(name)
	email = strings.TrimSpace(email)
	phone = strings.TrimSpace(phone)
	if name == "" {
		return Member{}, ErrInvalidName
	}
	if email == "" && phone == "" {
		return Member{}, ErrInvalidContact
	}
	if !IsAssignableRole(role) {
		return Member{}, fmt.Errorf("%w: %s", ErrInvalidRole, role)
	}
	now := time.Now().UTC()
	return Member{
		ID:           id,
		OwnerID:      scope.OwnerID,
		BrandID:      scope.BrandID,
		RestaurantID: scope.RestaurantID,
		Name:         name,
		Email:        email,
		Phone:        phone,
		Role:         role,
		Active:       true,
		CreatedAt:    now,
		UpdatedAt:    now,
	}, nil
}

// Scope is the minimal tenancy needed to construct a member; it mirrors
// tenancy.Scope but keeps the domain decoupled from the pkg/tenancy package.
type Scope struct {
	OwnerID      string
	BrandID      string
	RestaurantID string
}

// Activate flips the member active, rejecting a no-op so callers know whether a
// quota reservation is actually needed.
func (m *Member) Activate() error {
	if m.Active {
		return ErrAlreadyActive
	}
	m.Active = true
	m.UpdatedAt = time.Now().UTC()
	return nil
}

// Deactivate flips the member inactive, rejecting a no-op so callers know
// whether a quota release is actually needed.
func (m *Member) Deactivate() error {
	if !m.Active {
		return ErrAlreadyInactive
	}
	m.Active = false
	m.UpdatedAt = time.Now().UTC()
	return nil
}

// ChangeRole swaps the member's role, returning the previous role so the caller
// can release its reservation. It rejects an unassignable or unchanged role.
func (m *Member) ChangeRole(role commonv1.Role) (old commonv1.Role, err error) {
	if !IsAssignableRole(role) {
		return commonv1.Role_ROLE_UNSPECIFIED, fmt.Errorf("%w: %s", ErrInvalidRole, role)
	}
	if m.Role == role {
		return m.Role, ErrSameRole
	}
	old = m.Role
	m.Role = role
	m.UpdatedAt = time.Now().UTC()
	return old, nil
}

// QuotaKey is the entitlements quota key occupied by this member, e.g.
// "staff.waiter". Roles that do not occupy a per-role staff slot return "".
func (m Member) QuotaKey() string {
	return QuotaKeyFor(m.Role)
}

// ReservationID is the deterministic, idempotent reservation id for a member +
// role pair. Deriving it from the member id and role lets ReserveQuota /
// ReleaseQuota be retried safely and lets ChangeRole release exactly the slot it
// previously reserved.
func (m Member) ReservationID(role commonv1.Role) string {
	return ReservationIDFor(m.ID, role)
}

// ReservationIDFor builds the reservation id for an arbitrary member id + role.
func ReservationIDFor(memberID string, role commonv1.Role) string {
	return fmt.Sprintf("%s:%s", memberID, RoleSlug(role))
}

// QuotaKeyFor maps a role to its "staff.<role>" quota key, or "" if the role
// does not consume a staff quota slot.
func QuotaKeyFor(role commonv1.Role) string {
	if !IsAssignableRole(role) {
		return ""
	}
	return "staff." + RoleSlug(role)
}

// RoleSlug is the lowercase token for a role used in quota keys and reservation
// ids, e.g. ROLE_WAITER -> "waiter".
func RoleSlug(role commonv1.Role) string {
	switch role {
	case commonv1.Role_ROLE_MANAGER:
		return "manager"
	case commonv1.Role_ROLE_WAITER:
		return "waiter"
	case commonv1.Role_ROLE_KITCHEN:
		return "kitchen"
	case commonv1.Role_ROLE_CASHIER:
		return "cashier"
	case commonv1.Role_ROLE_BRAND_ADMIN:
		return "brand_admin"
	default:
		return strings.ToLower(strings.TrimPrefix(role.String(), "ROLE_"))
	}
}

// IsAssignableRole reports whether a role can be granted to a roster member.
// Platform admins, owners and anonymous customers are not outlet staff.
func IsAssignableRole(role commonv1.Role) bool {
	switch role {
	case commonv1.Role_ROLE_MANAGER,
		commonv1.Role_ROLE_WAITER,
		commonv1.Role_ROLE_KITCHEN,
		commonv1.Role_ROLE_CASHIER,
		commonv1.Role_ROLE_BRAND_ADMIN:
		return true
	default:
		return false
	}
}
