// Package domain holds the pure onboarding saga model and its step machine. It
// imports no infrastructure (no pgx, no connect, no nats) — only the standard
// library and the shared common/onboarding proto enums used as value types.
//
// The onboarding bounded context owns the signup -> go-live workflow as a
// RESUMABLE, IDEMPOTENT saga. An OnboardingState is a ledger of which steps have
// completed plus the ids the steps produced (owner/brand/restaurant/staff). A
// retried RPC consults the ledger and SKIPS work that is already done, reusing
// the stored ids — that is what makes every step idempotent.
package domain

import (
	"errors"
	"time"

	onboardingv1 "github.com/restorna/platform/gen/go/restorna/onboarding/v1"
)

// Typed domain errors. The grpc adapter maps these to Connect codes; the domain
// never panics for expected conditions.
var (
	ErrNotFound      = errors.New("onboarding not found")
	ErrInvalidInput  = errors.New("invalid onboarding input")
	ErrNotInScope    = errors.New("onboarding not in tenant scope")
	ErrOutOfOrder    = errors.New("onboarding step prerequisites not met")
	ErrAlreadyDone   = errors.New("onboarding already completed")
)

// State is the saga ledger for a single owner's onboarding. It records the
// completed steps and the ids each step produced so a retried call can skip
// already-done work. It is a pure value: the app loads it, mutates it through
// the methods below, and persists it.
type State struct {
	ID        string // onb_...
	OwnerID   string // own_... (set once the ACCOUNT step completes)
	UserID    string // usr_... owner's identity user
	BrandID   string // brnd_... (set by the BRAND step)
	LogoURL   string // uploaded brand logo (BRAND step)
	OutletID  string // out_... first restaurant (OUTLET step)
	PlanID    string // assigned plan (PLAN step)

	// completed is the set of steps the saga has finished. Stored as an ordered
	// slice in the proto/repo; modelled here as a set for O(1) idempotency checks.
	completed map[onboardingv1.Step]bool

	// Done is set when the saga reaches GOLIVE.
	Done      bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

// New builds a fresh saga state. The id is generated by the app (pkg/ids) so the
// domain stays infra-free.
func New(id string) State {
	now := time.Now().UTC()
	return State{
		ID:        id,
		completed: map[onboardingv1.Step]bool{},
		CreatedAt: now,
		UpdatedAt: now,
	}
}

// Rebuild reconstructs a State from persisted fields plus the completed-step
// list (as stored by the repo). Used by the pg adapter / fakes when loading.
func Rebuild(id, ownerID, userID, brandID, logoURL, outletID, planID string, completed []onboardingv1.Step, done bool, createdAt, updatedAt time.Time) State {
	set := make(map[onboardingv1.Step]bool, len(completed))
	for _, s := range completed {
		if s != onboardingv1.Step_STEP_UNSPECIFIED {
			set[s] = true
		}
	}
	return State{
		ID:        id,
		OwnerID:   ownerID,
		UserID:    userID,
		BrandID:   brandID,
		LogoURL:   logoURL,
		OutletID:  outletID,
		PlanID:    planID,
		completed: set,
		Done:      done,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
}

// stepOrder is the canonical saga order. STEP_MENU (M2) is not driven by this
// service; the saga goes ACCOUNT -> PLAN -> BRAND -> OUTLET -> SETTINGS -> TEAM
// -> GOLIVE.
var stepOrder = []onboardingv1.Step{
	onboardingv1.Step_STEP_ACCOUNT,
	onboardingv1.Step_STEP_PLAN,
	onboardingv1.Step_STEP_BRAND,
	onboardingv1.Step_STEP_OUTLET,
	onboardingv1.Step_STEP_SETTINGS,
	onboardingv1.Step_STEP_TEAM,
	onboardingv1.Step_STEP_GOLIVE,
}

// IsDone reports whether a step has already completed — the core idempotency
// check the app uses to skip already-done work on a retry.
func (s State) IsDone(step onboardingv1.Step) bool {
	return s.completed[step]
}

// Complete records a step as finished and advances the cursor. It is idempotent:
// completing an already-completed step is a no-op (no error) so retried RPCs are
// safe. The GOLIVE step also flips Done.
func (s *State) Complete(step onboardingv1.Step) {
	if s.completed == nil {
		s.completed = map[onboardingv1.Step]bool{}
	}
	s.completed[step] = true
	if step == onboardingv1.Step_STEP_GOLIVE {
		s.Done = true
	}
	s.UpdatedAt = time.Now().UTC()
}

// Require asserts that every prerequisite step has completed before a step runs,
// so the saga cannot be advanced out of order (e.g. SubmitBrand before
// StartOnboarding). Returns ErrOutOfOrder if a prerequisite is missing.
func (s State) Require(prereqs ...onboardingv1.Step) error {
	for _, p := range prereqs {
		if !s.completed[p] {
			return ErrOutOfOrder
		}
	}
	return nil
}

// Current returns the next step the saga should run: the first step in the
// canonical order that is not yet complete. When everything is done it returns
// STEP_GOLIVE.
func (s State) Current() onboardingv1.Step {
	for _, step := range stepOrder {
		if !s.completed[step] {
			return step
		}
	}
	return onboardingv1.Step_STEP_GOLIVE
}

// Completed returns the completed steps in canonical order (stable output for
// the wire message and the repo).
func (s State) Completed() []onboardingv1.Step {
	out := make([]onboardingv1.Step, 0, len(s.completed))
	for _, step := range stepOrder {
		if s.completed[step] {
			out = append(out, step)
		}
	}
	return out
}

// CanComplete reports whether the saga has reached the point where Complete (the
// GOLIVE transition) is allowed: the OUTLET must exist. TEAM is optional (an
// owner may go live before inviting anyone), so it is not a hard prerequisite.
func (s State) CanComplete() error {
	if s.Done {
		return ErrAlreadyDone
	}
	return s.Require(onboardingv1.Step_STEP_OUTLET, onboardingv1.Step_STEP_SETTINGS)
}
