apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "svc.fullname" . }}-config
  labels:
    {{- include "svc.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
  {{- range $k, $v := .Values.serviceURLs }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
